---
name: "create-release"

on: workflow_dispatch

jobs:
  tagged-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
      - run: npm install -g vsce

      - name: Package VS Code extension
        run: vsce package

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.vsix
